bell:
  animation: EaseOutExpo
  color: "#ffffff"
  duration: 0
colors:
  bright:
    black: "0x4d4d4d"
    blue: "0xcaa9fa"
    cyan: "0x9aedfe"
    green: "0x5af78e"
    magenta: "0xff92d0"
    red: "0xff6e67"
    white: "0xe6e6e6"
    yellow: "0xf4f99d"
  cursor:
    cursor: CellForeground
    text: CellBackground
  dim:
    black: "0x14151b"
    blue: "0x4d5b86"
    cyan: "0x59dffc"
    green: "0x1ef956"
    magenta: "0xff46b0"
    red: "0xff2222"
    white: "0xe6e6d1"
    yellow: "0xebf85b"
  indexed_colors: []
  normal:
    black: "0x000000"
    blue: "0xbd93f9"
    cyan: "0x8be9fd"
    green: "0x50fa7b"
    magenta: "0xff79c6"
    red: "0xff5555"
    white: "0xbfbfbf"
    yellow: "0xf1fa8c"
  primary:
    background: "0x282a36"
    foreground: "0xf8f8f2"
  selection:
    background: "0x44475a"
    text: CellForeground
  vi_mode_cursor:
    cursor: CellForeground
    text: CellBackground
cursor:
  style: Block
  thickness: 0.15
  unfocused_hollow: true
  vi_mode_style: None
debug:
  log_level: Warn
  persistent_logging: false
  print_events: false
  ref_test: false
  render_timer: false
draw_bold_text_with_bright_colors: false
env:
  TERM: xterm-256color
font:
  bold:
    family: monospace
    style: Bold
  bold_italic:
    family: monospace
    style: Italic
  glyph_offset:
    x: 0
    y: 0
  italic:
    family: monospace
    style: Italic
  normal:
    family: monospace
    style: Regular
  offset:
    x: 0
    y: 0
  size: 11
key_bindings: []
live_config_reload: false
mouse:
  double_click:
    threshold: 300
  hide_when_typing: false
  triple_click:
    threshold: 300
mouse_bindings: []
opacity:
  background_opacity: 1
scrolling:
  history: 65536
  multiplier: 3
selection:
  save_to_clipboard: false
  semantic_escape_chars: "',│`|:\"' ()[]{}<>"
window:
  class:
    general: Alacritty
    instance: Alacritty
  decorations: none
  dimensions:
    columns: 80
    lines: 24
  dynamic_padding: false
  dynamic_title: true
  gtk_theme_variant: None
  padding:
    x: 0
    y: 0
  position:
    x: 0
    y: 0
  startup_mode: Windowed
  title: Alacritty
